### PR TITLE
Adjusted Copilot System Console UI text

### PR DESCRIPTION
**Pull request by cwarnermm**
## Description

Reviewed Copilot System Console string text and provided editorial updates.

### CODE REVIEW

**Comment by cwarnermm** [comment]
@crspeller - the text line ``Global flag for all below settings`` - what does this mean? what exactly does this setting impact?

Also, not sure where to find the source code for this UI:
No Al bots added yet

I recommend changing ``AI copilot`` to ``Copilot``.

**Comment by crspeller** [comment]
@cwarnermm 
The text "Global flag for all below settings." Means that turning it off disables all the below settings. Let's not worry about this as these settings are experimental and are going to be replaced. 

Sneaky AI copilot! Added to this pr. 

The "team mebers" one was fixed a while ago. Where are you testing?

The view settings text is in the webapp not related to this plugin.

**Review by crspeller — APPROVED** [review]

**Comment by cwarnermm** [comment]
Thanks, @crspeller! I used a QA self-hosted testing environment to review the strings running 9.11.0 (Build Number: 10082049475).

**Comment by crspeller** [comment]
@cwarnermm That explains it! If you want the latest you can go on corpus.

**Comment by cwarnermm** [comment]
Just checked Corpus; no new editorial feedback to offer at this time.

**Comment by crspeller** [comment]
Great! Thanks @cwarnermm!

**Pull request merged**
